image: ruby:2.6

pipelines:
  custom: # Pipelines that are triggered manually
    show-uptime:
      - step:
          script:
            - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            - export AWS_DEFAULT_REGION="${AWS_REGION}"
            - gem install bundler:2.2.4
            - bundle install
            - ruby ssm-ops.rb -i development/Worker,development/Web -c "uptime"