image: ruby:2.6

pipelines:
  custom: # Pipelines that are triggered manually
    show-uptime:
      - step:
          script:
            - bundle install
            - ruby ssm-ops.rb -i development/Worker,development/Web -c "uptime"