image: ruby:2.5

pipelines:
  custom: # Pipelines that are triggered manually
    show-uptime:
      - step:
          script:
            - echo ${AWS_REGION}
            - gem install bundler:2.2.4
            - bundle install
            - ruby ssm-ops.rb -i development/Worker -c "uptime"