image: ruby:2.6

pipelines:
  custom: # Pipelines that are triggered manually
    show-uptime:
      - step:
          script:
            - gem install bundler:2.2.4
            - bundle install
            - ruby ssm-ops.rb -i development/Worker,development/Web -c "uptime"
      variables:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: "us-east-2"